# Ruby CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-ruby/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4.4-node-browsers
        environment:
          RAILS_ENV: test
          DATABASE_URL: postgresql://setlistdb@localhost/setlistb_test
          BUNDLE_PATH: vendor/cache
      - image: circleci/postgres:9.4
        environment:
          POSTGRES_USER: setlistdb
          POSTGRES_DB: setlistdb_test
          POSTGRES_PASSWORD: ""

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "Gemfile.lock" }}-{{ checksum "package.json" }}
          - v1-dependencies-

      - run: bundle install --jobs=4 --retry=3 --path vendor/bundle

      - run: yarn install

      - save_cache:
          paths:
            - ./vendor/bundle
            - node_modules
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}-{{ checksum "package.json" }}

      # Javascript tests!
      - run: yarn test

      # Database setup
      - run: bundle exec rails db:create db:schema:load db:migrate

      # Ruby tests!
      - run: bundle exec rake

      - store_test_results:
          path: test/reports
